### ISSUE TITLE
Past horoscopes

### ISSUE THREAD

**Issue by merrickqiu** [cse110-sp23-group5/cse110-sp23-group5#12]
Add in profiles for different people on the left.

**Comment by alextahan** [comment]
Add in ability to view past horoscopes using a sidebar on the left. This is similar to in ChatGPT how you can view past conversations.

Scrollable list of past horoscope queries/entries
- `<past-horoscope>` custom element

Clicking an entry will display the information for that horoscope on the main screen
Users can delete individual entries or clear all

For memory purposes, may need to limit number of entries stored
