### ISSUE TITLE
past entry card

### ISSUE THREAD

**Issue by alextahan** [cse110-sp23-group5/cse110-sp23-group5#19]
Custom HTML element for each card in the sidebar
Each card will display:
- date created
- birthday/sign of user
- preview of horoscope message

User actions:
- delete button: deletes the card and removes it from the list of past entries
- hover: user hovers over card and it highlights
- click: user clicks card, it highlights and shows full card on the main screen

**Comment by vivin2709** [comment]
Reviewed
